"""EXP3: walk-determination boundary for alkane skeletons (trees, max
degree <= 4).

Question: among trees with maximum degree <= 4 (carbon skeletons of
acyclic molecules), up to which order n do walk counts W_0..W_{n-1}
determine the adjacency spectrum? General trees break at n=22, but the
unique counterexample has a degree-5 vertex, i.e. is not a valid alkane.
The chemical boundary may be later (or the phenomenon absent).

Method (same two-stage protocol as walk_census_big.py):
  pass 1: walk fingerprints (W_0..W_{n-1}) mod two 24-bit primes for all
          max-degree<=4 trees (generated by filtering nx.nonisomorphic_trees)
  pass 2: inside every walk-collision class, EXACT verification:
          big-integer walk tuples + integral charpoly (Faddeev-LeVerrier)
          -> class is 'cospectral' or a genuine counterexample.

Output: results/chem_boundary_n{n}.json per n; summary printed.

Usage: python3 exp3_chem_boundary.py 4 24   (n from 4 to 24)
"""
import json
import sys
import time
from collections import defaultdict
from pathlib import Path

import networkx as nx
import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))  # for dgs_census if run from msr root
from dgs_census import charpoly_int  # noqa: E402

RESULTS = HERE.parent / "results"
RESULTS.mkdir(exist_ok=True)
P1, P2 = 16777213, 16777211
CHUNK = 20000


def walk_fp_mod(Ai, ps=(P1, P2)):
    n = len(Ai)
    outs = []
    for p in ps:
        Am = Ai % p
        v = np.ones(n, dtype=np.int64)
        w = [n % p]
        for _ in range(n - 1):
            v = (Am @ v) % p
            w.append(int(v.sum() % p))
        outs.append(tuple(w))
    return tuple(outs)


def exact_walks(G):
    n = G.number_of_nodes()
    al = [sorted(G.neighbors(v)) for v in range(n)]
    v = [1] * n
    W = [n]
    for _ in range(n - 1):
        nv = [0] * n
        for i in range(n):
            for j in al[i]:
                nv[j] += v[i]
        v = nv
        W.append(sum(v))
    return tuple(W)


def run(n):
    t0 = time.time()
    num = defaultdict(int)
    total = 0
    buf = []
    for G in nx.nonisomorphic_trees(n):
        if max(d for _, d in G.degree()) > 4:
            continue
        total += 1
        buf.append(walk_fp_mod(nx.to_numpy_array(G).astype(np.int64)))
        if len(buf) >= CHUNK:
            for wf in buf:
                num[wf] += 1
            buf.clear()
        if total % 100000 == 0:
            print(f"  [n={n}] {total} alkane trees "
                  f"({time.time()-t0:.0f}s)", flush=True)
    for wf in buf:
        num[wf] += 1
    hot = {f for f, c in num.items() if c > 1}
    print(f"[n={n}] pass1: {total} alkane trees, "
          f"{len(hot)} hot walk fps", flush=True)
    del num
    if not hot:
        out = {"n": n, "n_alkane_trees": total, "walk_collision_classes": 0,
               "noncospectral_classes": 0, "classes": [],
               "runtime_s": round(time.time() - t0, 1)}
        (RESULTS / f"chem_boundary_n{n}.json").write_text(
            json.dumps(out, indent=1))
        return out

    # pass 2: collect graph6 of trees in hot groups
    keep = defaultdict(list)
    for G in nx.nonisomorphic_trees(n):
        if max(d for _, d in G.degree()) > 4:
            continue
        wf = walk_fp_mod(nx.to_numpy_array(G).astype(np.int64))
        if wf in hot:
            keep[wf].append(
                nx.to_graph6_bytes(G, header=False).decode().strip())

    # exact refinement
    classes = []
    for wf, g6s in keep.items():
        sub = defaultdict(list)
        for g in g6s:
            G = nx.from_graph6_bytes(g.encode())
            w_exact = exact_walks(G)
            cp = tuple(charpoly_int(
                nx.to_numpy_array(G).astype(int).tolist()))
            sub[(w_exact,)].append(g)  # group by exact walks first
        for (w_exact,), group in sub.items():
            if len(group) < 2:
                continue
            # within exact-walk class, split by charpoly
            bycp = defaultdict(list)
            for g in group:
                G = nx.from_graph6_bytes(g.encode())
                cp = tuple(charpoly_int(
                    nx.to_numpy_array(G).astype(int).tolist()))
                bycp[cp].append(g)
            if len(bycp) > 1:
                # genuine counterexample: walk-equivalent, non-cospectral
                classes.append({
                    "n_members": len(group),
                    "n_spectra": len(bycp),
                    "members": [
                        {"g6": g,
                         "degseq": sorted(
                             (d for _, d in
                              nx.from_graph6_bytes(g.encode()).degree())),
                         "charpoly": [str(c) for c in cp]}
                        for cp, gs in sorted(bycp.items())
                        for g in gs],
                    "walk_tuple": [str(x) for x in w_exact],
                })
    out = {"n": n, "n_alkane_trees": total,
           "walk_collision_classes": len(keep),
           "noncospectral_classes": len(classes),
           "classes": classes, "runtime_s": round(time.time() - t0, 1)}
    (RESULTS / f"chem_boundary_n{n}.json").write_text(
        json.dumps(out, indent=1))
    print(f"[n={n}] DONE: {total} trees, {len(keep)} walk classes, "
          f"{len(classes)} NON-COSPECTRAL walk-equivalent classes",
          flush=True)
    return out


if __name__ == "__main__":
    lo, hi = int(sys.argv[1]), int(sys.argv[2])
    for n in range(lo, hi + 1):
        run(n)
